# Docker compose e2e tests

version: '3.8'

services:
  mock-register:
    container_name: mock-register
    image: mock-register
    hostname: mock-register
    ports: 
      - "7000:7000"
      - "7001:7001"
      - "7006:7006"
    # FIXME - MJS - comment out extra hosts (only used for debugging tests) or find some way to configure at runtime      
    extra_hosts:
      - "mock-data-holder-energy-e2e-tests:host-gateway"
      - "cdr-auth-server-e2e-tests:host-gateway"
    environment:
      - ASPNETCORE_ENVIRONMENT=Release
    # FIXME - MJS - commented out volumes below as volume is mounted as 1001:121 (vsts:docker) in build pipeline and causes issue with chown in dockerfile (appuser:appgroup), ie stops container from starting because of different user
    # volumes:
    #   - "./_temp/mock-register/tmp:/tmp"      
    healthcheck:
      test: wget --no-check-certificate --no-verbose --spider https://localhost:7006/health || exit 1
      timeout: 5s
      interval: 5s
      retries: 50      
    depends_on:
      mssql:
        condition: service_healthy

  mock-data-holder-energy:
    container_name: mock-data-holder-energy
    image: mock-data-holder-energy
    hostname: mock-data-holder-energy
    ports: 
      - "8100:8100"
      - "8101:8101"
      - "8102:8102"
      - "8105:8105"
      # auth ui
      - "3100:3100"
    # FIXME - MJS - comment out extra hosts (only used for debugging tests) or find some way to configure at runtime            
    extra_hosts:
      - "mock-data-holder-energy-e2e-tests:host-gateway"
      - "cdr-auth-server-e2e-tests:host-gateway"
    build:
      context: .
      dockerfile: Dockerfile
      args:
        # FIXME - MJS - "production" environment using Azure storage? not working? try development in meantime
        # target_environment: production
        target_environment: development
    environment:
      - ASPNETCORE_ENVIRONMENT=Release
      # tests need expiry of 3600
      - CdrAuthServer__AccessTokenExpirySeconds=3600
      # FIXME - MJS - is encryption ready?
      - CdrAuthServer__SupportJarmEncryption=false
    # FIXME - MJS - commented out volumes below as volume is mounted as 1001:121 (vsts:docker) in build pipeline and causes issue with chown in dockerfile (appuser:appgroup), ie stops container from starting because of different user
    # volumes:
    #   - "./_temp/mock-data-holder-energy/tmp:/tmp"      
    healthcheck:
      # FIXME - MJS - MDHE healthcheck (8105) should be updated to consider embedded CdrAuthServer health (8101). Meanwhile, just check both 8105, 8101 and 3100 (ui)
      # test: wget --no-check-certificate --no-verbose --spider https://localhost:8105/health || exit 1
      test: ((wget --no-check-certificate --no-verbose --spider https://localhost:8105/health) && (wget --no-check-certificate --no-verbose --spider https://localhost:8101/health) && (wget --no-check-certificate --no-verbose --spider https://localhost:3100)) || exit 1
      timeout: 5s
      interval: 5s
      retries: 50 
    depends_on:
      mssql:
        condition: service_healthy
      mock-register:
        condition: service_healthy

  cdr-auth-server-e2e-tests:
    container_name: cdr-auth-server-e2e-tests
    image: cdr-auth-server-e2e-tests
    ports: 
      - "9999:9999"
      - "9998:9998"
      - "9997:9997"
      - "9996:9996"
    environment:
      - ASPNETCORE_ENVIRONMENT=Release.Standalone
      # reconfigure URLs 
      - URL__CDRAuthServer_BaseUri=https://mock-data-holder-energy:8101
      - URL__CDRAuthServer_SecureBaseUri=https://mock-data-holder-energy:8102
      - URL__DH_MTLS_Gateway=https://mock-data-holder-energy:8102
      - URL__DH_TLS_IdentityServer=https://mock-data-holder-energy:8101
      - URL__DH_TLS_Public=https://mock-data-holder-energy:8101
      - URL__MDH_HOST=https://mock-data-holder-energy
      - Standalone=false
    volumes:
      - "./_temp/mock-data-holder-energy-cdr-auth-server-e2e-tests/testresults:/testresults"
    depends_on:
      mssql:
        condition: service_healthy
      mock-register:
        condition: service_healthy
      mock-data-holder-energy:
        condition: service_healthy

  mssql:
    container_name: sql1
    image: 'mcr.microsoft.com/mssql/server:2019-latest'
    ports: 
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Pa{}w0rd2019
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S . -U sa -P "Pa{}w0rd2019" -Q "SELECT 1" || exit 1 
      timeout: 5s
      interval: 5s
      retries: 20    
